# Generated by Django 6.0.6 on 2026-07-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='milestone',
            name='category',
            field=models.CharField(choices=[('Physical', 'Physical'), ('Language', 'Language'), ('Cognitive', 'Cognitive'), ('Social', 'Social'), ('Nutrition', 'Nutrition'), ('Sleep', 'Sleep')], max_length=100),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
